# roles/meta/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_meta_namespace }}"
    - "{{ openio_meta_sysconfig_dir }}/{{ openio_meta_type }}-{{ openio_meta_serviceid }}"
    - "{{ openio_meta_volume }}"
    - "/etc/oio/sds/{{ openio_meta_namespace }}/watch"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0750
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "/var/log/oio/sds/{{ openio_meta_namespace }}/{{ openio_meta_type }}-{{ openio_meta_serviceid }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0750
    recurse: true
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "meta.conf.j2"
      dest: "{{ openio_meta_sysconfig_dir }}/\
        {{ openio_meta_type }}-{{ openio_meta_serviceid }}/{{ openio_meta_type }}-{{ openio_meta_serviceid }}.conf"
    - src: "gridinit_meta.conf.j2"
      dest: "{{ openio_meta_gridinit_dir }}/{{ openio_meta_gridinit_file_prefix }}\
        {{ openio_meta_type }}-{{ openio_meta_serviceid }}.conf"
    - src: "watch-meta.yml.j2"
      dest: "{{ openio_meta_sysconfig_dir }}/watch/{{ openio_meta_type }}-{{ openio_meta_serviceid }}.yml"
  register: _meta_conf

- name: restart meta
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_meta_namespace}}-{{ openio_meta_type }}-{{openio_meta_serviceid}}
  when:
    - _meta_conf.changed
    - not openio_meta_provision_only
  tags: configure
...
